controllers/album.py
from flask import *
import extensions
import os, sys
import hashlib
from werkzeug.utils import secure_filename

UPLOAD_FOLDER = 'static/images'
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
album = Blueprint('album', __name__, template_folder='templates')

def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS
album = Blueprint('album', __name__, template_folder='templates')

@album.route('/album/edit', methods=['GET', 'POST'])
def album_edit_route():
    db = extensions.connect_to_database()
    cur = db.cursor()
    cur.execute('USE maindb')
    logged_in = False
    if 'username' in session:
        logged_in = True
    if logged_in:
        user = session['username']
    else:
        return redirect(url_for('main.login_route'))
    op = request.form.get('op')
    if not op:
        album_id = request.args.get('albumid')
        if not album_id:
            abort(404) #HERE
        album_id = int(album_id)
        if album_id < 1:
            abort(404)
        cur.execute('SELECT * FROM Album WHERE albumid = %d' % (album_id))
        album_exist = cur.fetchall()
        if not album_exist:
            abort(404)
        owner = album_exist[0]['username']
        if owner != user:
            abort(403)
        access = album_exist[0]['access']
        if access == "public":
            access = True
        else:
            access = False
        cur.execute('SELECT * FROM Contain WHERE albumid = %d' % (album_id))
        pics = cur.fetchall()
        cur.execute('SELECT * FROM Photo')
        photos = cur.fetchall()
        cur.execute('SELECT * FROM AlbumAccess WHERE albumid = %d' % (album_id))
        users_with_access = cur.fetchall()
        options = {
            "edit": True,
            "album_id": album_id,
            "photos": photos,
            "pics": pics,
            "users_with_access": users_with_access,
            "access": access
        }
        return render_template("album_edit.html", **options)
    else:
        album_id = request.form.get('albumid')
        if not album_id:
            abort(404) #HERE
        album_id = int(album_id)
        if album_id < 1:
            abort(404)
        cur.execute('SELECT * FROM Album WHERE albumid = %d' % (album_id))
        album_exist = cur.fetchall()
        if not album_exist:
            abort(404)
        if op == "delete":
            picid = request.form.get('picid')
            if not picid:
                abort(404)
            cur.execute('SELECT * FROM Contain WHERE picid = "%s"' % (picid))
            picids = cur.fetchall()
            if not picids:
                abort(404)
            cur.execute('DELETE FROM Contain WHERE picid = "%s"' % (picid))
            for pic in picids:
                cur.execute('SELECT format FROM Photo WHERE picid = "%s"' % pic['picid'])
                pic_format = cur.fetchall()[0]['format'];
                if not pic_format:
                    abort(404)
                cur.execute('DELETE FROM Photo WHERE picid = "%s"' % (picid))
                os.remove('static/images/' + picid + "." + str(pic_format))
            cur.execute('UPDATE Album SET lastupdated = CURRENT_TIME() WHERE albumid = "%s"' % (album_id))
        elif op == "add":
            file_name = request.files['file']
            temp_file_name = file_name.filename
            album_id = request.form.get('albumid')
            if not album_id:
                abort(404)
            album_id = int(album_id)
            if album_id < 1:
                abort(404)
            #reload page if the file format is bad 
            pic_format = temp_file_name[-3:]
            m = hashlib.md5(str(album_id) + temp_file_name)
            pic_id = m.hexdigest()
            final_file_name = str(pic_id) + "." + pic_format
            file_name.save(os.path.join(app.config['UPLOAD_FOLDER'], final_file_name))
            db = extensions.connect_to_database()
            cur = db.cursor()
            cur.execute('USE maindb')
            cur.execute('SELECT picid FROM Photo WHERE picid = "%s"' % (pic_id))
            existing_pic = cur.fetchall()
            if not existing_pic:
                cur.execute('INSERT INTO Photo (picid, format, picDate) VALUES("%s", "%s", CURRENT_TIME())' % (pic_id, pic_format))
                cur.execute('SELECT * FROM Contain')
                max_seq = cur.fetchall()
                max_num = 0;
                for pics in max_seq:
                    if int(pics['sequencenum']) > max_num:
                        max_num = int(pics['sequencenum'])
                max_num = max_num + 1
                cur.execute('INSERT INTO Contain (sequencenum, albumid, picid, caption) VALUES(%d, %d, "%s", "%s")' % (max_num, album_id, pic_id, ""))
                cur.execute('UPDATE Album SET lastupdated = CURRENT_TIME() WHERE albumid = "%s"' % (album_id))
        elif op == "grant":
            username = request.form.get('username')
            cur.execute('SELECT * FROM User WHERE username = "%s"' % (username))
            name = cur.fetchall()
            if not name:
                abort(404)
            cur.execute('SELECT * FROM Album WHERE albumid = %d' % (album_id))
            album_exist = cur.fetchall()
            access = album_exist[0]['access']
            if access == "private":
                cur.execute('INSERT INTO AlbumAccess (albumid, username) VALUES (%d, "%s")' % (album_id, username))
            cur.execute('UPDATE Album SET lastupdated = CURRENT_TIME() WHERE albumid = "%s"' % (album_id))
        elif op =="revoke":
            username = request.form.get('username')
            cur.execute('SELECT * FROM User WHERE username = "%s"' % (username))
            name = cur.fetchall()
            if not name:
                abort(404)
            cur.execute('DELETE FROM AlbumAccess WHERE username = "%s"' % (username))
            cur.execute('UPDATE Album SET lastupdated = CURRENT_TIME() WHERE albumid = "%s"' % (album_id))
        elif op =="access":
            access = request.form.get('access')
            cur.execute('UPDATE Album SET lastupdated = CURRENT_TIME() WHERE albumid = "%s"' % (album_id))
            cur.execute('UPDATE Album SET access = "%s" WHERE albumid = "%s"' % (access, album_id))
            if access == "public":
                cur.execute('DELETE FROM AlbumAccess WHERE albumid = "%s"'% (album_id))

    return redirect(url_for('album.album_edit_route', albumid=album_id))

    
@album.route('/album')
def album_route():
    return render_template("album.html")

controllers/albums.py
from flask import *
import extensions
import os, sys

albums = Blueprint('albums', __name__, template_folder='templates')

@albums.route('/albums/edit', methods=['POST', 'GET'])
def albums_edit_route():
    db = extensions.connect_to_database()
    cur = db.cursor()
    logged_in = False
    if 'username' in session:
        logged_in = True
    if logged_in:
        user = session['username']
    else:
        return redirect(url_for('main.login_route'))
    cur.execute('use maindb')
    cur.execute('SELECT * FROM User WHERE username = "%s"' % (user))
    user_exist = cur.fetchall()
    if not user_exist:
        abort(404)
    op = request.form.get('op')
    if not op:
        cur.execute('SELECT * FROM Album WHERE username = "%s"' % (user))
        albums = cur.fetchall()
        cur.execute('SELECT * FROM AlbumAccess WHERE username = "%s"' % (user))
        access_albums = cur.fetchall()
        cur.execute('SELECT * FROM Album')
        all_albums = cur.fetchall()
        options = {
            "access_albums": access_albums,
            "edit": True,
            "username": user,
            "albums": albums,
            "all_albums": all_albums
        }
        return render_template("albums.html", **options)

    elif op == "delete":
        album_id = int(request.form.get('albumid'))
        cur.execute('SELECT * FROM Contain WHERE albumid = %d' % (album_id))
        picids = cur.fetchall()
        cur.execute('DELETE FROM Contain WHERE albumid = %d' % (album_id))
        for pic in picids:
            cur.execute('SELECT format FROM Photo WHERE picid = "%s"' % pic['picid'])
            format = cur.fetchall()[0]['format']
            cur.execute('DELETE FROM Photo WHERE picid = "%s"' % pic['picid'])
            os.remove('/static/images/' + pic['picid'] + "." + str(format) )
        cur.execute('DELETE FROM Album WHERE albumid = %d' % (album_id))
        cur.execute('DELETE FROM AlbumAccess WHERE albumid = %d' % (album_id))
    else:
        title = request.form.get('title')
        cur.execute('INSERT INTO Album VALUES(NULL, "%s", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), "%s", "%s")' % (title, user, "private"))

    return redirect(url_for('albums.albums_edit_route', username=user))



@albums.route('/albums')
def albums_route():
    logged_in = False
    user = request.args.get('username')
    if not user:
        if 'username' in session:
            logged_in = True
        if logged_in:
            user = session['username']
        else:
            return redirect(url_for('main.login_route'))
    db = extensions.connect_to_database()
    cur = db.cursor()
    cur.execute('use maindb')
    cur.execute('SELECT * FROM User WHERE username = "%s"' % (user))
    user_exist = cur.fetchall()
    if not user_exist:
        abort(404)
    cur.execute('SELECT * FROM Album WHERE username = "%s"' % (user))
    albums = cur.fetchall()
    if logged_in:
        cur.execute('SELECT * FROM AlbumAccess WHERE username = "%s"' % (user))
        access_albums = cur.fetchall()

        options = {
            "access_albums": access_albums,
            "edit": False,
            "logged_in": logged_in,
            "username": user,
            "albums": albums
        }
        return render_template("albums.html", **options)
    
    else:
        cur.execute('SELECT * FROM Album WHERE username = "%s" and access = "%s"' % (user, "public"))
        public_albums = cur.fetchall()
        
        options = {
            "edit": False,
            "logged_in": logged_in,
            "username": user,
            "albums": albums,
            "public_albums": public_albums
        }
        
        return render_template("albums.html", **options)

controllers/main.py
from flask import *
import extensions
import uuid
import hashlib
import re

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def main_route():
	db = extensions.connect_to_database()
	cur = db.cursor()
	cur.execute('use maindb')
	if 'username' in session:
		user = session['username']
		cur.execute('SELECT * FROM User WHERE username = "%s"' % (user))
		user_db = cur.fetchall()
		first_name = user_db[0]['firstname']
		last_name = user_db[0]['lastname']
		cur.execute('SELECT * FROM Album WHERE access = "%s"' % ('public'))
		public_albums = cur.fetchall()
		cur.execute('SELECT * FROM AlbumAccess WHERE username = "%s"' % (user))
		user_access_albums = cur.fetchall()
		cur.execute('SELECT * FROM Album WHERE username = "%s" AND access = "%s"' % (user, 'private'))
		private_albums = cur.fetchall()
		cur.execute('SELECT * From Album')
		all_albums = cur.fetchall()
		options = {
			"logged_in": True,
			"firstname" : first_name,
			"lastname" : last_name,
			"public_albums": public_albums,
			"user_access_albums": user_access_albums,
			"private_albums": private_albums,
			"all_albums": all_albums
		}
		return render_template("index.html", **options)
	else:
		cur.execute('SELECT * FROM Album WHERE access = "%s"' % ('public'))
		albums = cur.fetchall()
		cur.execute('SELECT username FROM User')
		users = cur.fetchall()
		options = {
			"logged_in": False,
			"users" : users,
			"public_albums" : albums
		}
		return render_template("index.html", **options)

@main.route('/login', methods=['GET', 'POST'])
def login_route():
	return render_template("login.html")

@main.route('/logout', methods=['POST'])
def logout_route():
	return redirect(url_for('main.main_route'))

@main.route('/user', methods=['GET', 'POST'])
def newUser_route():
	if 'username' in session:
		return redirect(url_for('main.user_edit_route'))
	return render_template("newUser.html")

@main.route('/user/edit', methods=['GET', 'POST'])
def user_edit_route():
	if 'username' in session:
		return render_template("userEdit.html")
	else:
		return redirect(url_for('main.login_route'))


	

	

controllers/pic.py
from flask import *
import extensions

pic = Blueprint('pic', __name__, template_folder='templates')

@pic.route('/pic', methods=['GET','POST'])
def pic_route():
		return render_template("album.html")	

templates/album_edit.html
{% extends "base.html" %}
{% block content %}
    <h1>ALBUM</h1>
    <p class="important">
      Welcome!
    </p>
        <form action="{{ url_for('album.album_edit_route')}}" method="POST">
        <input type="radio" name="access" value="public" id="album_edit_public_radio" > Public<br/>
        <input type="radio" name="access" value="private" id="album_edit_private_radio" > Private<br/>
        <input type="hidden" name ="albumid" value="{{album_id}}">
        <input type="submit" name="op" value="access" id="album_edit_access_submit"></form>
        <table>
            <tr><th>Username</th><th>Update Access</th></tr> 
            {% for user in users_with_access %}
                <tr><td>{{user['username']}} </td>
                <td><form action="{{ url_for('album.album_edit_route')}}" method="POST">
                <input type="hidden" name="albumid" value="{{album_id}}">
                <input type="hidden" name="username" value = "{{user['username']}}">
                <input type="submit" name="op" value="revoke" id="album_edit_revoke_{{user['username']}}"></form></td>
                </tr>
            {% endfor %}

        <tr>
         <form action="{{ url_for('album.album_edit_route')}}" method="POST">
           <tr><td>New:
             <input type="text" name = "username" id="album_edit_grant_input"> </td>
             <td><input type="hidden" name="albumid" value="{{album_id}}">
             <input type="submit" name="op" value="grant" id="album_edit_grant_submit"></td>
         </form>
        </tr>
        </table>
        {% for pic in pics %}
            {% for photo in photos %}
                {% if pic['picid'] == photo['picid'] %}
                     <div>
                        <a href="{{ url_for('pic.pic_route', picid = pic['picid'])}}" id="pic_{{pic['picid']}}_link"><img src="/static/images/{{pic['picid']}}.{{photo['format']}}" height="75" width="75" display:"inline-block"></img></a>
                        <form action=" {{url_for('album.album_edit_route') }}" method="POST">   
                            <input type ="hidden" value="{{pic['picid']}}" name="picid" >
                            <input type="hidden" value="{{album_id}}" name="albumid">
                            <input type ="submit" value="delete" name="op" id="delete_pic_{{pic['picid']}}">
                        </form>
                    </div>

                {% endif %}
            {% endfor %}
        {% endfor %}
        <form action="{{url_for('album.album_edit_route', albumid=album_id) }}" method="POST" enctype="multipart/form-data">
        <input type ="hidden" value= "{{album_id}}" name="albumid">
        <input type ="file" name="file" id="file_input">
        <input type="submit" value= "add" name="op" id ="file_submit"> </form>
{% endblock %}

templates/albums.html
{% extends "base.html" %}
{% block content %}
    <h1>ALBUMS {{username}}</h1>
    <p class="important">
      Welcome!
    </p>
    {% if edit %}
            <div>
                <table>
                    {% for album in albums %}
                    <tr>
                        <td> {{album['title']}} </td>
                        <td> 
                            <a href="{{ url_for('album.album_edit_route', albumid=album['albumid']) }}"><input type ="hidden" value="edit" id="album_edit_{{album['albumid']}}_link" method="get"> Edit Album</a>
                            

                            <form action=" {{url_for('albums.albums_edit_route') }}" method="POST">   
                            <input type ="hidden" value="{{album['albumid']}}" name="albumid" >
                            <input type="hidden" value="{{album['username']}}" name="username" >
                            <input type ="submit" name="op" value="delete" id="delete_album_{{album['albumid']}}"></form>

                        </td>

                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div>
                <form action="{{ url_for('albums.albums_edit_route') }}" method="POST">
                    <input type="text" id="album_add_name" name="title">
                    <input type="hidden" name="username" value="{{username}}">
                    <input type="submit" name="op" value="add" id="album_add_submit">
                </form>
            </div>

    {% else %}
        {%if logged_in%}
            <a href="{{ url_for('albums.albums_edit_route')}}"> <input type="hidden" id="user_albums_edit_{{username}}" method="get"> Edit Albums</a>
            {% for album in albums %}
                <div>
                    {{album['title']}}
                    <a href="{{ url_for('album.album_route', albumid=album['albumid']) }}" id="album_{{album['albumid']}}_link">View Album</a>
                </div>
            {% endfor %}

        {%else%}
            {%for album in public_albums%}
                <div>
                {{album['title']}}
                    <a href="{{ url_for('album.album_route', albumid=album['albumid']) }}" id="album_{{album['albumid']}}_link">View Album</a>
                </div>
            {%endfor%}
        {%endif%}
    
    {% endif %}
    
{% endblock %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <meta name="author" content=" Julia, Jenny, and Jack">
    <link rel="stylesheet" href="/static/css/style.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <title>EECS485</title>
</head>
<body>
  <header> This is a website for users to be able to view and edit picture albums. </header>
  {% if session['username'] %}
  	Logged in as {{session['firstname']}} {{session['lastname']}}
  	<a href="{{url_for('main.main_route')}}" id="nav_home">Home</a>
  	<a href="{{url_for('albums.albums_route')}}" id="nav_albums">My Albums</a>
  	<a href="{{ url_for('main.user_edit_route')}}" id="nav_edit">Edit Account</a>
  	<form id="logout_form">
  		<input type="submit" id="nav_logout" value="Logout">
  	</form>
    <div id="error_mess"></div>
    <script type="text/javascript">
      $('#logout_form').submit( function(e) {
          e.preventDefault();
          $.ajax({
              type: 'POST',
              url: 'api/v1/logout',
              success: function() {
                window.location.href ="/p2gkisj6/p3";
              },
              error: function(errors) {
                str = JSON.parse(JSON.stringify(errors));
                str = str.responseText;
                str = JSON.parse(str);
                str = str.errors;
                for(x in str){
                    $('#error_mess').append('<p class="error">' + str[x].message + '</div>')
                }
              }
          });
      });
    </script>
  {% else %}
    <a href="#" id="login_link">Login</a>
    <script type="text/javascript">
      $('#login_link').on("click", function(){
          curr_url = window.location.href;
          temp = window.location.href;
          temp = temp.split("/p3")[0]; 
          window.location.href = temp + "/p3/login?url=" + curr_url
      });
  </script>

      

  {% endif %}
  <div class="center">
    {% block content %}{% endblock %}
  </div>
  <script type="text/javascript" src="/static/js/main.js"></script>
  <footer>Created by Julia, Jenny, and Jack </footer>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Photo Repo</h1>
    <p class="center">
      Welcome!
    </p>
    <ul>
    {% if logged_in %}
        {% for album in private_albums %}
            <div>
                <a href="{{ url_for('album.album_route', albumid=album['albumid'])}}" id="album_{{album['albumid']}}_link">{{album['title']}}</a>
            </div>
        {% endfor %}
        {% for album in user_access_albums %}
            {% for temp in all_albums%}
                {%if temp['albumid'] == album['albumid']%}
                    <div>
                        <a href="{{ url_for('album.album_route', albumid=album['albumid'])}}" id="album_{{album['albumid']}}_link">{{temp['title']}}</a>
                    </div>
                {%endif%}
            {%endfor%}
        {% endfor %}
    {% else %}
        <a href="{{ url_for('main.newUser_route')}}" id="home_user_create">New User</a>
        <a href="{{ url_for('main.login_route')}}" id="home_login">Log In</a>
        {% for user in users %}
            <div>
                {{ user['username'] }}
                <a href="{{ url_for('albums.albums_route', username=user['username'])}}" id="user_albums_{{user['username']}}">View Albums</a>
            </div>
        {% endfor %}
    {% endif %}

    {% for album in public_albums %}
        <div>
            <a href="{{ url_for('album.album_route', albumid=album['albumid'])}}" id="album_{{album['albumid']}}_link">{{album['title']}}</a>
        </div>
    {% endfor %}
    </ul>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
    <h1>EECS485 PROJECT 1</h1>
    <p class="center">
      Login
    </p>
    <ul>
        <div id="error_mess"></div>
        <form id="login_user">   
            Username: <input type ="text" name="username" id="login_username_input">
            Password: <input type="password" name="password" id="login_password_input">
            <input type="submit" value="submit" id="login_submit">
        </form>

        <script type="text/javascript">
            $(document).ready( function(e) {
                $('#login_link').hide();
            });
            $('#login_user').submit( function(e) {
                e.preventDefault();
                $('.error').remove();
                $.ajax({
                    type: 'POST',
                    contentType: "application/json; charset=UTF-8",
                    data: JSON.stringify(
                            {'username': $("#login_username_input").val(),
                            'password': $("#login_password_input").val()}),
                    url: 'api/v1/login',
                    success: function(data) {
                        temp = window.location.href;
                        temp = temp.split("url=")[1];
                        if(temp){
                            window.location.href = temp;
                        }
                        else{
                            window.location.href ="/p2gkisj6/p3";
                        }

                    },
                    error: function(errors) {
                        str = JSON.parse(JSON.stringify(errors));
                        str = str.responseText;
                        str = JSON.parse(str);
                        str = str.errors;
                        for(x in str){
                            $('#error_mess').append('<p class="error">' + str[x].message + '</div>')
                        }

                    }
                });
            });
        </script>
     </ul>
{% endblock %}

templates/newUser.html
{% extends "base.html" %}
{% block content %}
    <h1>EECS485 PROJECT 1</h1>
    <p class="center">
    New User
    </p>
    <ul>
        <div id="error_mess"></div>
        <br>
        <form id="new_user">   
            Username: <input type ="text" name="username" id="new_username_input"><br/>
            First Name: <input type ="text" name="firstname" id="new_firstname_input"><br/>
            Last Name: <input type ="text" name="lastname" id="new_lastname_input"><br/>
            Password: <input type="password" name="password1" id="new_password1_input"><br/>
            Confirm Password: <input type="password" name="password2" id="new_password2_input"><br/>
            Email: <input type ="text" name="email" id="new_email_input"><br/>
            <input type="submit" id="new_submit">Submit
        </form>
        <script type="text/javascript">
            $('#new_user').submit( function(e) {
                $('.error').remove();
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    contentType: "application/json; charset=UTF-8",
                    data: JSON.stringify({'username': $("#new_username_input").val(),
                            'firstname': $("#new_firstname_input").val(),
                            'lastname': $("#new_lastname_input").val(),
                            'password1': $("#new_password1_input").val(),
                            'password2': $("#new_password2_input").val(),
                            'email': $("#new_email_input").val()}),
                    url: 'api/v1/user',
                    success: function(data) {
                        temp = window.location.href;
                        temp = temp.split("/p3")[0];
                        window.location.href = temp + "/p3/login";
                    },
                    error: function(errors) {
                        str = JSON.parse(JSON.stringify(errors));
                        str = str.responseText;
                        str = JSON.parse(str);
                        str = str.errors;
                        for(x in str){
                            $('#error_mess').append('<p class="error">' + str[x].message + '</div>')
                        }

                    }
                });
            });
        </script>
    </ul>
{% endblock %}

templates/pic.html
{% extends "base.html" %}
{% block content %}
	{% for p in pic %}
			<img src="/static/images/{{p['picid']}}.{{p['format']}}" height="300" size="300"></img>
			<br>
			<p id="pic_{{p['picid']}}_caption"> {{pic_in_contain[0]['caption']}} </p>
			{%if owner%}
				<form action="{{url_for('pic.pic_route')}}" method="POST">
				<input type="hidden" name="picid" value="{{p['picid']}}" >
				<input type="text" name="caption" id="pic_caption_input">
				<input type="submit" name="op" value="Change caption" id="pic_caption_submit"> </form>
			{%endif%}

	{% endfor %}
	{% if prevID != '' %}

		<a href="{{ url_for('pic.pic_route', picid = prevID)}}" id="prev_pic">Prev Pic</a>
	{% endif %}
	{% if nextID != '' %}
		<a href="{{ url_for('pic.pic_route', picid = nextID)}}" id="next_pic">Next Pic</a>
	{% endif %}
	<br>
	<a href="{{ url_for('album.album_route', albumid = album_id) }}" id="parent_album">Back to Album</a>
{% endblock %}

templates/userEdit.html
{% extends "base.html" %}
{% block content %}
    <h1>EECS485 PROJECT 1
    <p class="center">
     Edit User
    </h1>
    <div id="error_mess"></div>

    <ul>
        <form action="{{url_for('main.user_edit_route')}}" id="update_user" method="POST"><br>
            New First Name: <input type="text" name="firstname" id="update_firstname_input"><br>
            New Last Name: <input type="text" name="lastname" id="update_lastname_input"><br>
            New Email: <input type ="text" name="email" id="update_email_input"><br>
            New Password: <input type="password" name="password1" id="update_password1_input"><br>
            Confirm New Password: <input type="password" name="password2" id="update_password2_input"><br>
            <input type="submit" value="Submit" id="update_submit">
        </form>
    </ul>

    <script type="text/javascript">
        $(document).ready( function(e) {
            $.ajax({
                type: 'GET',
                contentType: "application/json; charset=UTF-8",
                url: 'api/v1/user',
                success: function(data) {
                    str = JSON.parse(JSON.stringify(data));
                    str = str.data;
                    $("#update_firstname_input").attr("value", str.firstname);
                    $('#update_lastname_input').attr("value", str.lastname);
                    $('#update_email_input').attr("value", str.email);
                },
                error: function() {
                    temp = window.location.href;
                    temp = temp.split("/p3")[0];
                    window.location.href = temp +"/p3/login";
                }
            });
        });
        $('#update_user').submit( function(e) {
            $('.error').remove();
            e.preventDefault();
            $.ajax({
                type: 'PUT',
                contentType: "application/json; charset=UTF-8",
                data: JSON.stringify({
                        'firstname': $("#update_firstname_input").val(),
                        'lastname': $("#update_lastname_input").val(),
                        'password1': $("#update_password1_input").val(),
                        'password2': $("#update_password2_input").val(),
                        'email': $("#update_email_input").val()}),
                url: 'api/v1/user',
                success: function(data) {
                    temp = window.location.href;
                    temp = temp.split("/p3")[0];
                    window.location.href = temp + "/p3/user/edit";
                },
                error: function(errors) {
                    str = JSON.parse(JSON.stringify(errors));
                    str = str.responseText;
                    str = JSON.parse(str);
                    str = str.errors;
                    for(x in str){
                        $('#error_mess').append('<p class="error">' + str[x].message + '</div>')
                    }
                }
            });
        });
    </script>
{% endblock %}